# Generated by Django 3.2.5 on 2021-07-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
