# Generated by Django 3.2.5 on 2021-07-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
