# Generated by Django 3.2.5 on 2021-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_authormodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='title',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
