# Generated by Django 3.2.5 on 2021-07-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsmodel',
            name='follower',
            field=models.IntegerField(max_length=100),
        ),
    ]
