# Generated by Django 3.2.5 on 2021-07-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_factsmodel_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactsModel',
        ),
    ]
